SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `audit_logs`;
DROP TABLE IF EXISTS `notifications`;
DROP TABLE IF EXISTS `comments`;
DROP TABLE IF EXISTS `likes`;
DROP TABLE IF EXISTS `collections`;
DROP TABLE IF EXISTS `user_study_records`;
DROP TABLE IF EXISTS `content_permissions`;
DROP TABLE IF EXISTS `course_units`;
DROP TABLE IF EXISTS `courses`;
DROP TABLE IF EXISTS `articles`;
DROP TABLE IF EXISTS `module_pages`;
DROP TABLE IF EXISTS `modules`;
DROP TABLE IF EXISTS `user_tags`;
DROP TABLE IF EXISTS `role_permissions`;
DROP TABLE IF EXISTS `user_roles`;
DROP TABLE IF EXISTS `permissions`;
DROP TABLE IF EXISTS `roles`;
DROP TABLE IF EXISTS `admin_users`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `log_configs`;
DROP TABLE IF EXISTS `wechat_configs`;
SET FOREIGN_KEY_CHECKS = 1;
